---
title: "Đồ án kết thúc học phần"
author:
  - "Vũ Hà Thư"
  - "Nguyễn Đình Mai Vi"
  - "Trần Việt Hà"
date: "07/2026"

output:
  pdf_document:
    toc: false
    toc_depth: 2
    number_sections: true
    latex_engine: xelatex
    keep_tex: false
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    df_print: paged

fontsize: 11pt
geometry: margin=2cm
mainfont: "Times New Roman"

bibliography: references.bib
link-citations: true
nocite: |
  @*

header-includes:
  - \usepackage{float}
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{booktabs}
  - \usepackage{graphicx}
  - \usepackage{underscore}
  - \let\maketitle\relax
  - \renewcommand{\contentsname}{Mục lục}
  - \setcounter{tocdepth}{2}
  - \definecolor{darkgreen}{HTML}{006400}

editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
# "here" xac dinh thu muc goc repo (noi co .git) bat ke working directory
# hien tai la gi, giup duong dan toi cac child document va du lieu on dinh
# du phien R co bi anh huong boi trang thai cu (vd chay chunk tuong tac
# truoc do) hay khong.
if (!requireNamespace("here", quietly = TRUE)) install.packages("here")

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```

```{=latex}
\begin{titlepage}
\thispagestyle{empty}
\begin{center}

\vspace*{1cm}
{\LARGE\bfseries TRƯỜNG ĐẠI HỌC KHOA HỌC TỰ NHIÊN}\\[0.3em]
{\LARGE\bfseries KHOA TOÁN -- TIN HỌC}

\vspace{2cm}

{\Large\bfseries BÁO CÁO}\\[0.5em]
{\LARGE\bfseries MÔ HÌNH HÓA THỐNG KÊ}\\[0.7em]
\rule{0.6\textwidth}{0.5pt}\\[0.6em]
{\large \textbf{Đồ án kết thúc học phần}}

\vspace{2cm}

{\large Giảng viên hướng dẫn: \textbf{[TODO: Tên giảng viên]}}

\vspace{1.5cm}

{\large\bfseries Nhóm [TODO: XX]}

\vspace{0.6em}
{\small
\begin{tabular}{|l|c|p{5.5cm}|c|}
\hline
\textbf{Họ và Tên} & \textbf{Mã số HV} & \textbf{Công việc} & \textbf{Mức độ hoàn thành} \\
\hline
{[}TODO{]} & {[}TODO{]} & {[}TODO{]} & {[}TODO{]}\% \\
\hline
{[}TODO{]} & {[}TODO{]} & {[}TODO{]} & {[}TODO{]}\% \\
\hline
{[}TODO{]} & {[}TODO{]} & {[}TODO{]} & {[}TODO{]}\% \\
\hline
\end{tabular}
}

\vfill
{\large TP. Hồ Chí Minh, 2026}
\end{center}
\end{titlepage}

\tableofcontents
\newpage
```

```{r child=here::here("Part_1_CommunityCrime", "Part_1_CommunityCrime.Rmd")}
```

\newpage

```{r child=here::here("Part_2_SalaryDS", "Part_2_SalaryDS.Rmd")}
```

\newpage

Phần 3 (Bộ dữ liệu tự chọn) tạm thời chưa được đưa vào bản PDF này: `Part_3_FreeChoice/output/Part_1_FreeChoi_123.Rmd` cần file dữ liệu `../DoAn/bike_sharing_hour.csv` hiện chưa có sẵn. Đặt `eval = TRUE` ở chunk dưới đây (và bổ sung file dữ liệu) để đưa Phần 3 trở lại bản PDF.

```{r child=here::here("Part_3_FreeChoice", "Part_3_FreeChoice.Rmd"), eval=FALSE}
```

# Tài liệu tham khảo
